name: Generate ASCII Artwork

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update apt cache
        run: sudo apt-get update -y

      - name: Install cowsay
        run: sudo apt-get install -y cowsay

      - name: Generate dragon ASCII
        run: cowsay -f dragon "Run for cover, I am a DRAGON...RAWR" | tee dragon.txt

      - name: (Optional) Sleep 30s
        run: sleep 30

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dragon
          path: dragon.txt

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dragon
          path: .

      - name: (Optional) Sleep 10s
        run: sleep 10

      - name: Verify file contains 'dragon'
        run: grep -i "dragon" dragon.txt

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dragon
          path: .

      - name: Read file
        run: cat dragon.txt

      - name: Deploy
        run: echo "Deploying ... .. .."
