name: Exploring Variables and Secrets

on:
  push:
  ################ Environment variables at WORKFLOW level ################
env:
  CONTAINER_REGISTRY: docker.io
  DOCKER_USERNAME: ibhagat
  IMAGE_NAME: github-actions-nginx

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
        contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Docker Build
        run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest .

      - name: Docker Login
        env:
          DOCKER_PASSWORD: HLaU4p4HSxsZ
        run: echo docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Docker Publish
        run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Docker Run
        run: docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest .
