name: Workflow Filters and Activities

on:
  workflow_dispatch:
  push:
    branches:
      - main
#    branches-ignore:
#      - feature/*
#      - test/**
  pull_request:
    types:
      - opened
      - closed
    paths-ignore:
      - README.md  # workflow runs only if files other than README.md are changed
    branches:
      - main       # only runs on pull requests targeting 'main'

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Show Event
        run: |
          echo "This workflow ran for event: ${{ github.event_name }}"
